# Generated by Django 4.1.1 on 2022-10-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
